server:
  port: 8001
spring:
  application:
    name: gateway
  profiles:
    active: dev
  security:
    user:
      name: wish
      password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
